backend:
  name: github
  repo: iamsamsmall/fccc
  branch: netlify # Branch to update (optional; defaults to master)
  site_domain: fundercommitmentclimatechange.org

media_folder: "assets/uploads"

collections:
  - name: "Section" # Used in routes, e.g. /admin/collections/blog
    label: "Section" # Used in the UI
    folder: "_sections" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    delete: false # Stop users from deleting
    editor:
      preview: false # Hide preview
    slug: "{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Order", name: "order", widget: "hidden"}
      - {label: "Layout", name: "include", widget: "hidden"}
